### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by Evgenii-Gorbushin** [tofutree23/use-captcha#1]
Hello,
Could you please add support for React 18?
<img width="473" alt="Screenshot_2022 06 09_02" src="https://user-images.githubusercontent.com/43174102/172817579-7b8a49d9-dda6-47d1-bab3-d1b7731e094a.png">

**Comment by tofutree23** [comment]
Hello! Thank you for the information. 

Updated and Released in `v0.2.0`

Best regards
